### ISSUE TITLE
curseforge를 통한 install시 정상적으로 실행되지 않음

### ISSUE THREAD

**Issue by jaehunkim** [RyuaNerin/WoWcl#3]
curseforge로 wowcl 2021.04.08.0511 업데이트

![image](https://user-images.githubusercontent.com/8697531/114013527-9a8d2f80-98a2-11eb-9c63-8095972c1e21.png)

addon하위 `wowcl`디렉토리 이름을 `WoWcl`로 변경하니 정상적으로 실행됨

**Comment by RyuaNerin** [comment]
반영하겠습니다.

**Comment by RyuaNerin** [comment]
제가 Release 할 때에 압축 파일 내에 디렉토리 이름을 `WoWcl` 로 대소문자를 구분해서 입력했으나, CurseForge 측에서 대소문자를 무시하고 생성하는 것 같습니다. CurseForge 에서 문제를 확인해봐야 할 것 같습니다.

![image](https://user-images.githubusercontent.com/6766851/114111378-df51ae80-9914-11eb-9ab8-53ca011ae711.png)

**Comment by RyuaNerin** [comment]
혹시 몰라서 `wowcl.lua` `wowcl.xml` `wowcl.toc` 파일의 대소문자를 구분하였습니다.

**Comment by RyuaNerin** [comment]
주변 지인들께 정상적인 이용이 가능하다고 확인받았습니다. 다시 문제가 발생하시면 코멘트 남겨주시면 감사하겠습니다.

**Comment by jaehunkim** [comment]
최신 업데이트후 정상작동합니다 🙇‍♂️
